name: Classificador Financeiro

on:
  push:
    branches: [ "main",narrativa-ia" ]
    paths:
      - 'entrada.csv' # IMPORTANTE: O robô só acorda se você mexer neste arquivo!
  workflow_dispatch:

permissions:
  contents: write # IMPORTANTE: Dá permissão para o robô salvar o arquivo atualizado

jobs:
  classificacao:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        ref: narrativa-ia

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install pandas google-generativeai requests

    - name: Executar Classificador
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python classificador_ia.py

    - name: Salvar Mudanças no GitHub
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
        # Garante que estamos na branch correta antes de commitar
        git checkout ${{ github.ref_name }}
        
        # Adiciona o arquivo CSV modificado
        git add *.csv
        
        # Faz o commit
        git commit -m "Auto: Atualização de dados via IA" || echo "Nada a commitar"
        
        # EMPURRA PARA A MESMA BRANCH QUE DISPAROU O ROBÔ
        git push origin ${{ github.ref_name }}