name: Classificador Financeiro

on:
  push:
    branches: [ "narrativa-ia" ]
  workflow_dispatch:

jobs:
  classificacao:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        ref: narrativa-ia

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install pandas google-generativeai requests

    - name: Executar Classificador
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python classificador_ia.py